[package]
name = "discograph"
version = "0.1.0"
authors = ["Asher Baker <asherkin@limetech.io>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
lru = "0.5"
env_logger = "0.7"
nom = "5"
serde = "1"
serde_json = "1"
anyhow = "1"

[dependencies.serenity]
git = "https://github.com/asherkin/serenity"
branch = "piespy"
default-features = false
features = ["client", "gateway", "http", "model", "rustls_backend"]

#[patch."https://github.com/asherkin/serenity"]
#serenity = { path = "../serenity" }
