[package]
name = "piespy-rs"
version = "0.1.0"
authors = ["Asher Baker <asherkin@limetech.io>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
lru = "0.5.3"
env_logger = "0.7.1"
nom = "5.1.2"

[dependencies.serenity]
git = "https://github.com/asherkin/serenity"
branch = "piespy"
default-features = false
features = ["client", "gateway", "http", "model", "rustls_backend"]

[dependencies.petgraph]
version = "0.5.1"
default-features = false
features = ["serde-1", "graphmap"]

#[patch."https://github.com/asherkin/serenity"]
#serenity = { path = "../serenity" }
